// Run with: node verify.cjs (Node.js standard library only).
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const noop = () => {};
const element = {innerHTML:'',textContent:'',focus:noop,addEventListener:noop,classList:{add:noop,remove:noop,toggle:noop},open:false};
const storage = new Map();
const ctx = vm.createContext({window:{},document:{querySelector:()=>element,querySelectorAll:()=>[],addEventListener:noop},localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)},location:{hash:''},setTimeout:()=>0,clearTimeout:noop,Date,Intl,console});
vm.runInContext(fs.readFileSync(path.join(__dirname,'dist/questions.js'),'utf8'),ctx);
const source = fs.readFileSync(path.join(__dirname,'dist/app.js'),'utf8').split("window.addEventListener('hashchange'")[0];
vm.runInContext(source,ctx);
const run = text => vm.runInContext(text,ctx);
assert.equal(run('QUESTIONS.length'),180);
assert.equal(run('new Set(QUESTIONS.map(q=>q.id)).size'),180);
assert.equal(run('QUESTIONS.every(q=>q.options.length===4 && q.options.every(o=>typeof o==="string" && o.length>0) && q.correct.length===1 && q.correct[0]>=0 && q.correct[0]<4)'),true);
assert.equal(run('byId.get(74).correct[0]'),3);
run('config.shuffle=false; config.count=10; start(); view="quiz";');
assert.equal(run('validSession(data.session)'),true);
run('choose(2); choose(0);');
assert.equal(run('data.session.answers[1]'),2,'Practice answers lock after feedback');
run('data.session.index=1;choose(0);');
assert.deepEqual(JSON.parse(run('JSON.stringify(grade(data.session))')),{correct:1,wrong:1,blank:8,total:10,percent:10});
assert.equal(run('data.wrong.includes(2)'),true);
run('finish();');
assert.equal(run('data.history.length'),1);
assert.equal(run('data.session'),null);
assert.equal(JSON.parse(storage.get('onluyen-180-v1')).history[0].answers['1'],2);
run('start([2]);view="quiz";choose(1);finish();');
assert.equal(run('data.wrong.includes(2)'),false,'Correct retry removes the wrong-answer marker');
run('config.mode="exam";start();view="quiz";choose(0);choose(2);');
assert.equal(run('data.session.answers[1]'),2,'Exam answers may be changed');
run('data.session.deadline=Date.now()-100;tick();');
assert.equal(run('data.session'),null,'Expired exam submits automatically');
assert.equal(run('data.history.length'),3);
assert.equal(run('new Set(shuffle(QUESTIONS.map(q=>q.id))).size'),180);
assert.equal(run('validSession({...data.history[0],ids:[999]})'),false);
assert.equal(run('validSession({...data.history[0],answers:{1:8}})'),false);
run('start([74]);data.session.mode="exam";renderQuiz();');
assert.equal(element.innerHTML.includes('chuyển thành D'),false,'Source notes must not reveal keys before exam submission');
assert.equal(run('fold("ĐỒNG Chí")'),'dong chi');
run('view="bank";search="THANH PHO ho chi minh";');
assert.equal(run('bankQuestions().some(q=>q.id===1)'),true,'Find keywords present only in answer options');
run('search="dai hoi 2030";');
assert.equal(run('bankQuestions().some(q=>q.id===3)'),true,'Search multiple keywords across question and options');
run('search="2030";');
assert.ok(run('bankQuestions().length')>0,'Years are searchable keywords, not nonexistent question IDs');
run('search="74";');
assert.equal(run('JSON.stringify(bankQuestions().map(q=>q.id))'),'[74]');
run('search="   ";');
assert.equal(run('bankQuestions().length'),180);
run('search="qwertyasdfzxcv";');
assert.equal(run('bankQuestions().length'),0);
run('view="saved";data.saved=[1];search="ho chi minh";');
assert.equal(run('JSON.stringify(bankQuestions().map(q=>q.id))'),'[1]','Search respects saved-question filter');
assert.equal(run('highlight("Đồng chí",["dong"])'),'<mark>Đồng</mark> chí');
assert.equal(run('highlight("Đoàn kết",["doan","oan"])'),'<mark>Đoàn</mark> kết','Overlapping matches merge');
assert.equal(run('highlight("ĐỒNG ĐỒNG",["dong"])'),'<mark>ĐỒNG</mark> <mark>ĐỒNG</mark>');
assert.equal(run('highlight("Đồng chí".normalize("NFD"),["dong"])'),'<mark>Đồng</mark> chí'.normalize('NFD'),'Decomposed Vietnamese characters highlight without splitting accents');
assert.equal(run('highlight("<img onerror=x>",["img"])'),'&lt;<mark>img</mark> onerror=x&gt;','Untrusted content stays escaped');
assert.equal(run('highlight("A [.*] B",["[.*]"])'),'A <mark>[.*]</mark> B','Search terms are literal, not regular expressions');
run('view="bank";search="dai hoi 2030";renderBankResults();');
assert.equal(element.innerHTML.includes('<mark>'),true);
assert.equal(element.innerHTML.includes('<details open>'),true,'Matching options are visible immediately');
console.log('PASS: quiz logic and keyword search, Vietnamese accents, answer-only matches, years, IDs, highlights, escaping and search results.');
