// Run with: node verify.cjs (Node.js standard library only).
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const noop = () => {};
const element = {innerHTML:'',textContent:'',focus:noop,addEventListener:noop,classList:{add:noop,remove:noop,toggle:noop},open:false};
const storage = new Map();
const ctx = vm.createContext({window:{},document:{querySelector:()=>element,querySelectorAll:()=>[],addEventListener:noop},localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)},location:{hash:''},setTimeout:()=>0,clearTimeout:noop,Date,Intl,console});
vm.runInContext(fs.readFileSync(path.join(__dirname,'dist/questions.js'),'utf8'),ctx);
const source = fs.readFileSync(path.join(__dirname,'dist/app.js'),'utf8').split("window.addEventListener('hashchange'")[0];
vm.runInContext(source,ctx);
const run = text => vm.runInContext(text,ctx);
assert.equal(run('QUESTIONS.length'),180);
assert.equal(run('new Set(QUESTIONS.map(q=>q.id)).size'),180);
assert.equal(run('QUESTIONS.every(q=>q.options.length===4 && q.options.every(o=>typeof o==="string" && o.length>0) && q.correct.length===1 && q.correct[0]>=0 && q.correct[0]<4)'),true);
assert.equal(run('byId.get(74).correct[0]'),3);
run('config.shuffle=false; config.count=10; start(); view="quiz";');
assert.equal(run('validSession(data.session)'),true);
run('choose(2); choose(0);');
assert.equal(run('data.session.answers[1]'),2,'Practice answers lock after feedback');
run('data.session.index=1;choose(0);');
assert.deepEqual(JSON.parse(run('JSON.stringify(grade(data.session))')),{correct:1,wrong:1,blank:8,total:10,percent:10});
assert.equal(run('data.wrong.includes(2)'),true);
run('finish();');
assert.equal(run('data.history.length'),1);
assert.equal(run('data.session'),null);
assert.equal(JSON.parse(storage.get('onluyen-180-v1')).history[0].answers['1'],2);
run('start([2]);view="quiz";choose(1);finish();');
assert.equal(run('data.wrong.includes(2)'),false,'Correct retry removes the wrong-answer marker');
run('config.mode="exam";start();view="quiz";choose(0);choose(2);');
assert.equal(run('data.session.answers[1]'),2,'Exam answers may be changed');
run('data.session.deadline=Date.now()-100;tick();');
assert.equal(run('data.session'),null,'Expired exam submits automatically');
assert.equal(run('data.history.length'),3);
assert.equal(run('new Set(shuffle(QUESTIONS.map(q=>q.id))).size'),180);
assert.equal(run('validSession({...data.history[0],ids:[999]})'),false);
assert.equal(run('validSession({...data.history[0],answers:{1:8}})'),false);
run('start([74]);data.session.mode="exam";renderQuiz();');
assert.equal(element.innerHTML.includes('chuyển thành D'),false,'Source notes must not reveal keys before exam submission');
console.log('PASS: 180 questions / four choices, scoring, blanks, locked practice, editable exam, retry, persistence, auto-submit and validation.');
